theme: jekyll-theme-cayman
title: Junior Game Developer (Unity / C#)  
description: Hello! I'm Riccardo Cruanes Rossini, an Italian programmer with experience in back-end Java development.  
            I develop gameplay systems and prototypes in Unity, focusing on modular C# code and simple pixel art to visualize mechanics.
