theme: jekyll-theme-cayman
title: Riccardo Cruanes Rossini Portfolio
description: Game developer focused on gameplay systems, crafting clean, maintainable code while learning and testing new mechanics in Unity, including some pixel art for visual polish.
